name: CI

on:
  push:
    branches: [ "main", "dev/ci_project" ]
  pull_request:
    branches: [ "main", "dev/ci_project" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Building
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . 
          
      - name: Linters
        working-directory: ${{github.workspace}}
        run: ./linters/run.sh
      
      - name: Upload our build dir
        uses: actions/upload-artifact@v3
        with:
          name: build-dir
          path: build
  
  test:
    
    needs: [build]
    
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v3
      
#       - name: Building
#         run: |
#           mkdir build
#           cd build
#           cmake ..
#           cmake --build . 
      - name: Donwload build dir
        uses: actions/download-artifact@v3
        with:
          name: build-dir
      
      - name: Testing
        run: ./project/tests/project_tests
      - name: valgridn install
        run: apt install valgrind
        
      - name: valgrind check
        run: valgrind --tool=memcheck --leak-check=yes --error-exitcode=1 ./${PROJECT_NAME} 
#         Project name указываем тот, что мы создаём
