name: CI

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
jobs:
  RunLinters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install cpplint
        run: pip install cpplint
        
      - name: Install cppcheck
        run: sudo apt install cppcheck
      
      - name: check files
        run: python cppLintCheck.py

  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Building
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . 

      - name: Upload our build dir
        uses: actions/upload-artifact@v3
        with:
          name: build-dir
          path: build

  RunTests:
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download build dir
        uses: actions/download-artifact@v3
        with:
          name: build-dir
          path: build

      - name: Permissions for tests
        run: sudo chmod 777 ./build/tests/tests

      - name: Test
        run: sudo ctest -VV
        working-directory: build
        
