name: CI

on:
  push:
    branches: 
      - dev/ci_project 
      - main
  pull_request:
    branches: [ "main", "dev/ci_project" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: install cpplint
        run: pip install cpplint
      - name: check files
        run: cpplint  ${{github.workspace}}/src/main.cpp
#       We can add more files or create Make file to this later
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Building
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . 
          
#       - name: Linters
#         working-directory: ${{github.workspace}}
#         run: ./linters/run.sh
      
      - name: Upload our build dir
        uses: actions/upload-artifact@v3
        with:
          name: build-dir
          path: build
  
  test:
    
    needs: [build]
    
    runs-on: ubuntu-latest
    
    steps:
      
      - uses: actions/checkout@v3
      
      - name: Building
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build . 
      
#       - name: Testing
#         run: ctest -C
      - name: valgridn install
        run: sudo apt install valgrind
        
      - name: valgrind check
        run: valgrind --tool=memcheck --leak-check=yes --error-exitcode=1 ./ci_project 
#         Project name указываем тот, что мы создаём
